spring.application.name=guiasdespacho
server.port=8080

# Configuracion de RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Enviar mensajes fallidos a cola DLQ en vez de reenviar
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Configuracion base de datos H2 (en memoria)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraciones HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# Session config
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# Configuracion de login de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

# Issuer de JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI}

# Importar variables de entorno desde archivo .env para despliegue local
spring.config.import=optional:file:.env[.properties]